### PR TITLE
Fix #176: build error on Windows

### LINKED ISSUE #176: Does not build on Windows with dub
When building with dub on vscode on Windows, I get the following errors:
```
C:\Users\User\AppData\Local\dub\packages\dpp-0.2.1\dpp\source\dpp\runtime\app.d(160,44): Error: module `core.sys.posix.stdlib` import mkstemp not found
C:\Users\User\AppData\Local\dub\packages\dpp-0.2.1\dpp\source\dpp\runtime\app.d(118,33): Error: template instance `dpp.runtime.app.translationText!(File)` error instantiating
C:\Users\User\AppData\Local\dub\packages\dpp-0.2.1\dpp\source\dpp\runtime\app.d(19,9):        instantiated from here: preprocess!(File)
```
The last version that builds is v0.1.17. Seems to be caused by commit #169.

### PR DESCRIPTION
**Pull request by lempiji**
Fix build error with reference to atilaneves/libclang (close #176)

### CODE REVIEW

**Comment by atilaneves** [comment]
Thanks!
